import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' pt-24 min-h-screen'}>
        <nav className='flex flex-row justify-between items-center fixed top-0 w-full bg-transparent backdrop-blur px-16 py-5 border-b-2 border-white/10 border-solid'>
          <h1 className='text-5xl cursor-pointer'>
            <span className='border-[#FFA364] text-[#FFA364]'>Pyt</span>
            <span className='border-[#FFEBD2] text-[#FFEBD2]'>h</span>
            <span className='border-[#AF4F41] text-[#AF4F41]'>ern</span>
          </h1>
          <div className='flex flex-row gap-8 items-center'>
            <Link className="hover:border-b-2" href="/about-us">About Us</Link>
            <Link className="hover:border-b-2" href="/login">Log In</Link>
            <Link className="hover:border-b-2" href="/signup">Sign Up</Link>
          </div>
        </nav>
        {children}
        <div className='absolute bottom-0 w-full border-t-2 border-white/10 border-solid p-2 bg-transparent'>
          <p>Pythern - 2023</p>
        </div>
      </body>
    </html>
  )
}
